package hcs.view;

import com.github.britooo.looca.api.core.Looca;
import com.github.britooo.looca.api.util.Conversor;
import hcs.coleta.dados.DadosCpu;
import hcs.coleta.dados.DadosMemoriaRam;
import hcs.coleta.dados.InserirDados;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.TimerTask;
import java.awt.BorderLayout;
import java.util.Timer;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYDataset;
import org.jfree.ui.RefineryUtilities;
import hcs.graficos.GraficoCpuTask;
import hcs.graficos.GraficoCpu;

/**
 *
 * @author ricar
 */
public final class Cpu extends javax.swing.JFrame {
    
    GraficoCpu grafico = new GraficoCpu("Monitoramento CPU");
    
    /**
     * Creates new form Cpu
     */
    public Cpu() {
        
        URL caminhoIcone = getClass().getResource("/assets/hcs.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        
        initComponents();
        
        //grafico
        grafico.pack();
        RefineryUtilities.centerFrameOnScreen(grafico);
        Grafico();
        GraficoCpuTask taskCpu = new GraficoCpuTask(grafico);
        Timer timer = new Timer("Grafico linha");
        timer.schedule(taskCpu, 0, 3000);
        
        
        Looca looca = new Looca();
        Conversor conversor = new Conversor();
        
        DadosCpu dadosCpu = new DadosCpu();
        DadosMemoriaRam dadosRam = new DadosMemoriaRam();
        
        InserirDados insertDados = new InserirDados();

        informacoesCpu();
        
        Timer temporizador = new Timer();
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                insertDados.inserirDadosCpu();
                insertDados.inserirDadosRam();
                insertDados.inserirDadosTemperatura();
                
            }
        };

        temporizador.schedule(task, 0, 1000);
    }
    
    public void Grafico()  {

        setDefaultCloseOperation(EXIT_ON_CLOSE);

        final XYDataset dataset = grafico.gerarDataSetInicial();

        JFreeChart chart = grafico.gerarGrafico(dataset);
                graficoCpu.setVisible(true);

                ChartPanel pane = new ChartPanel(chart);
                pane.setDomainZoomable(true);
                
                pane.setVisible(true);
                
                   graficoCpu.setLayout(new BorderLayout());
                   
                     graficoCpu.add(pane, BorderLayout.NORTH);
                
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnSistema = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panelHome = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        graficoCpu = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        panelNucleos = new javax.swing.JPanel();
        lblLogicos = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblFisicos = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        panelModelo = new javax.swing.JPanel();
        lblModelo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hardware Control System - Dashboard Consumo CPU");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(4, 30, 84));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hardware Control System");
        jLabel4.setPreferredSize(new java.awt.Dimension(250, 250));
        panelHeader.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 40));

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 60));

        panelMenu.setBackground(new java.awt.Color(9, 22, 112));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(25, 120, 220));
        jButton1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/thermometerIconWhite.png"))); // NOI18N
        jButton1.setText("TEMP ");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setRolloverEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelMenu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 140, 70));

        btnSistema.setBackground(new java.awt.Color(25, 120, 220));
        btnSistema.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnSistema.setForeground(new java.awt.Color(255, 255, 255));
        btnSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/managementIconWhite.png"))); // NOI18N
        btnSistema.setText("SISTEMA");
        btnSistema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSistema.setRolloverEnabled(false);
        btnSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSistemaActionPerformed(evt);
            }
        });
        panelMenu.add(btnSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 70));

        jButton3.setBackground(new java.awt.Color(0, 75, 200));
        jButton3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cpuIconWhite.png"))); // NOI18N
        jButton3.setText("CPU");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setRolloverEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelMenu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 70));

        jButton4.setBackground(new java.awt.Color(25, 120, 220));
        jButton4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hardDiscIconWhite.png"))); // NOI18N
        jButton4.setText("DISCO");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setRolloverEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelMenu.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, 70));

        jButton5.setBackground(new java.awt.Color(25, 120, 220));
        jButton5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ramIconWhite.png"))); // NOI18N
        jButton5.setText("RAM");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setRolloverEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelMenu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, 70));

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 180, 660));

        panelHome.setBackground(new java.awt.Color(110, 124, 255));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo2.setBackground(new java.awt.Color(56, 93, 118));

        jLabel11.setBackground(new java.awt.Color(204, 255, 204));
        jLabel11.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Núcleos:");
        jLabel11.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout lblTitulo2Layout = new javax.swing.GroupLayout(lblTitulo2);
        lblTitulo2.setLayout(lblTitulo2Layout);
        lblTitulo2Layout.setHorizontalGroup(
            lblTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTitulo2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lblTitulo2Layout.setVerticalGroup(
            lblTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblTitulo2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelHome.add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 160, 70));

        javax.swing.GroupLayout graficoCpuLayout = new javax.swing.GroupLayout(graficoCpu);
        graficoCpu.setLayout(graficoCpuLayout);
        graficoCpuLayout.setHorizontalGroup(
            graficoCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        graficoCpuLayout.setVerticalGroup(
            graficoCpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        panelHome.add(graficoCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 860, 430));

        lblTitulo1.setBackground(new java.awt.Color(56, 93, 118));

        jLabel9.setBackground(new java.awt.Color(204, 255, 204));
        jLabel9.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Modelo:");
        jLabel9.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout lblTitulo1Layout = new javax.swing.GroupLayout(lblTitulo1);
        lblTitulo1.setLayout(lblTitulo1Layout);
        lblTitulo1Layout.setHorizontalGroup(
            lblTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblTitulo1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        lblTitulo1Layout.setVerticalGroup(
            lblTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTitulo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelHome.add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 70));

        panelNucleos.setBackground(new java.awt.Color(56, 93, 118));
        panelNucleos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogicos.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblLogicos.setForeground(new java.awt.Color(255, 255, 255));
        panelNucleos.add(lblLogicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 70, 70));

        jLabel10.setBackground(new java.awt.Color(204, 255, 204));
        jLabel10.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 25)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total:");
        jLabel10.setPreferredSize(new java.awt.Dimension(250, 250));
        panelNucleos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 120, 70));

        jLabel12.setBackground(new java.awt.Color(204, 255, 204));
        jLabel12.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 25)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Físicos:");
        jLabel12.setPreferredSize(new java.awt.Dimension(250, 250));
        panelNucleos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 70));

        lblFisicos.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblFisicos.setForeground(new java.awt.Color(255, 255, 255));
        panelNucleos.add(lblFisicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 60, 70));

        jLabel13.setBackground(new java.awt.Color(204, 255, 204));
        jLabel13.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Lógicos:");
        jLabel13.setPreferredSize(new java.awt.Dimension(250, 250));
        panelNucleos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 140, 70));

        lblTotal.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        panelNucleos.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 90, 70));

        panelHome.add(panelNucleos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 680, 70));

        panelModelo.setBackground(new java.awt.Color(56, 93, 118));
        panelModelo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblModelo.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(255, 255, 255));
        panelModelo.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 660, 60));

        panelHome.add(panelModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 680, 70));

        getContentPane().add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 900, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Cpu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSistemaActionPerformed
        new Sistema().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSistemaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Disco().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Ram().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Temp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cpu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cpu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cpu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cpu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cpu().setVisible(true);
            }
        });
    }
    
    public void informacoesCpu() {
        // Informações CPU
        DadosCpu dadosCpu = new DadosCpu();
        
        lblModelo.setText(dadosCpu.getModeloCpu());
        
        lblFisicos.setText(dadosCpu.getQtdNucleosFisicos().toString());
        
        lblLogicos.setText(dadosCpu.getQtdNucleosVirtuais().toString());
        
        lblTotal.setText(dadosCpu.getQtdTotalNucleos().toString());
        

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSistema;
    private javax.swing.JPanel graficoCpu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblFisicos;
    private javax.swing.JLabel lblLogicos;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JPanel lblTitulo1;
    private javax.swing.JPanel lblTitulo2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelModelo;
    private javax.swing.JPanel panelNucleos;
    // End of variables declaration//GEN-END:variables
}
