
package hcs.view;

import com.github.britooo.looca.api.core.Looca;
import com.github.britooo.looca.api.util.Conversor;
import hcs.coleta.dados.DadosCpu;
import hcs.coleta.dados.DadosMemoriaRam;
import hcs.coleta.dados.DadosSistema;
import hcs.coleta.dados.DadosTemperatura;
import hcs.coleta.dados.InserirDados;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author ricar
 */
public class Temp extends javax.swing.JFrame {

    /**
     * Creates new form Temp
     */
    public Temp() 
    {
        URL caminhoIcone = getClass().getResource("/assets/hcs.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitulo);
        
        initComponents();

        Looca looca = new Looca();
        Conversor conversor = new Conversor();
        
        DadosCpu dadosCpu = new DadosCpu();
        DadosMemoriaRam dadosRam = new DadosMemoriaRam();
        
        InserirDados insertDados = new InserirDados();

        informacoesTemperatura();

        Timer temporizador = new Timer();
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                insertDados.inserirDadosCpu();
                insertDados.inserirDadosRam();
                
            }
        };

        temporizador.schedule(task, 0, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnSistema = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        panelHome = new javax.swing.JPanel();
        lblTitulo3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panelSistema = new javax.swing.JPanel();
        lblCelsius = new javax.swing.JLabel();
        panelSistema2 = new javax.swing.JPanel();
        lblKelvin = new javax.swing.JLabel();
        panelArquitetura = new javax.swing.JPanel();
        lblFaren = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(4, 30, 84));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hardware Control System");
        jLabel4.setPreferredSize(new java.awt.Dimension(250, 250));
        panelHeader.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 40));

        getContentPane().add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 60));

        panelMenu.setBackground(new java.awt.Color(9, 22, 112));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(25, 120, 220));
        jButton1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/thermometerIconWhite.png"))); // NOI18N
        jButton1.setText("TEMP ");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setRolloverEnabled(false);
        panelMenu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 140, 70));

        btnSistema.setBackground(new java.awt.Color(0, 75, 200));
        btnSistema.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        btnSistema.setForeground(new java.awt.Color(255, 255, 255));
        btnSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/managementIconWhite.png"))); // NOI18N
        btnSistema.setText("SISTEMA");
        btnSistema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSistema.setRolloverEnabled(false);
        panelMenu.add(btnSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 70));

        jButton3.setBackground(new java.awt.Color(25, 120, 220));
        jButton3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/cpuIconWhite.png"))); // NOI18N
        jButton3.setText("CPU");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setRolloverEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelMenu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 70));

        jButton4.setBackground(new java.awt.Color(25, 120, 220));
        jButton4.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hardDiscIconWhite.png"))); // NOI18N
        jButton4.setText("DISCO");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setRolloverEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelMenu.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, 70));

        jButton5.setBackground(new java.awt.Color(25, 120, 220));
        jButton5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/ramIconWhite.png"))); // NOI18N
        jButton5.setText("RAM");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setRolloverEnabled(false);
        panelMenu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, 70));

        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 180, 520));

        panelHome.setBackground(new java.awt.Color(110, 124, 255));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo3.setBackground(new java.awt.Color(56, 93, 118));

        jLabel8.setBackground(new java.awt.Color(204, 255, 204));
        jLabel8.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Farenheight:");
        jLabel8.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout lblTitulo3Layout = new javax.swing.GroupLayout(lblTitulo3);
        lblTitulo3.setLayout(lblTitulo3Layout);
        lblTitulo3Layout.setHorizontalGroup(
            lblTitulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblTitulo3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        lblTitulo3Layout.setVerticalGroup(
            lblTitulo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTitulo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelHome.add(lblTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        lblTitulo1.setBackground(new java.awt.Color(56, 93, 118));

        jLabel9.setBackground(new java.awt.Color(204, 255, 204));
        jLabel9.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Celsius:");
        jLabel9.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout lblTitulo1Layout = new javax.swing.GroupLayout(lblTitulo1);
        lblTitulo1.setLayout(lblTitulo1Layout);
        lblTitulo1Layout.setHorizontalGroup(
            lblTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblTitulo1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        lblTitulo1Layout.setVerticalGroup(
            lblTitulo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTitulo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelHome.add(lblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 330, 70));

        lblTitulo2.setBackground(new java.awt.Color(56, 93, 118));

        jLabel7.setBackground(new java.awt.Color(204, 255, 204));
        jLabel7.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kelvin:");
        jLabel7.setPreferredSize(new java.awt.Dimension(250, 250));

        javax.swing.GroupLayout lblTitulo2Layout = new javax.swing.GroupLayout(lblTitulo2);
        lblTitulo2.setLayout(lblTitulo2Layout);
        lblTitulo2Layout.setHorizontalGroup(
            lblTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblTitulo2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        lblTitulo2Layout.setVerticalGroup(
            lblTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTitulo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelHome.add(lblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        panelSistema.setBackground(new java.awt.Color(56, 93, 118));
        panelSistema.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCelsius.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblCelsius.setForeground(new java.awt.Color(255, 255, 255));
        panelSistema.add(lblCelsius, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 240, 70));

        panelHome.add(panelSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 330, 70));

        panelSistema2.setBackground(new java.awt.Color(56, 93, 118));
        panelSistema2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblKelvin.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblKelvin.setForeground(new java.awt.Color(255, 255, 255));
        panelSistema2.add(lblKelvin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 240, 70));

        panelHome.add(panelSistema2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 330, 70));

        panelArquitetura.setBackground(new java.awt.Color(56, 93, 118));
        panelArquitetura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFaren.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblFaren.setForeground(new java.awt.Color(255, 255, 255));
        panelArquitetura.add(lblFaren, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 250, 70));

        panelHome.add(panelArquitetura, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 330, 70));

        getContentPane().add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 740, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Cpu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Disco().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temp().setVisible(true);
            }
        });
    }
    
    public void informacoesTemperatura() {
        // Informações Sistema
        DadosTemperatura dadosTemperatura = new DadosTemperatura();
        
        lblCelsius.setText(dadosTemperatura.getTemperaturaCelsius().toString());
        lblFaren.setText(dadosTemperatura.getTemperaturaFaren().toString());
        lblKelvin.setText(dadosTemperatura.getTemperaturaKelvin().toString());
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSistema;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCelsius;
    private javax.swing.JLabel lblFaren;
    private javax.swing.JLabel lblKelvin;
    private javax.swing.JPanel lblTitulo1;
    private javax.swing.JPanel lblTitulo2;
    private javax.swing.JPanel lblTitulo3;
    private javax.swing.JPanel panelArquitetura;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelSistema;
    private javax.swing.JPanel panelSistema2;
    // End of variables declaration//GEN-END:variables
}
